gmbolt:
  restart: always
  image: chrisreis53/gmsec_node:2-bolt
  command: ["java","-jar","/GMSEC_API/bin/bolt.jar","port=9100"]
  ports:
    - "9100:9100"

gm_kerbal_adaptor:
  restart: always
  build: ./gmsec_ubuntu
  volumes:
    - ../GMSEC_API-4.2:/GMSEC_API
  environment:
    - LD_LIBRARY_PATH=/GMSEC_API/bin
  links:
    - gmbolt
  command: ["/GMSEC_API/bin/gm_kerbal_adaptor","server=gmbolt:9100","connectiontype=gmsec_bolt","loglevel=NONE"]

gm_kerbal_tlm_provider:
  restart: always
  build: ./gmsec_ubuntu
  volumes:
    - ../GMSEC_API-4.2:/GMSEC_API
  environment:
    - LD_LIBRARY_PATH=/GMSEC_API/bin
  links:
    - gmbolt
  ports:
    - "8081:8081"
  command: ["/GMSEC_API/bin/gm_telemetry_server","server=gmbolt:9100","connectiontype=gmsec_bolt","loglevel=NONE"]

gmsub:
  restart: always
  build: ./gmsec_sub
  environment:
    - LD_LIBRARY_PATH=/GMSEC_API/bin
  links:
    - gmbolt
    #- rabbitmq
  command: ["/GMSEC_API/bin/gmsub","server=gmbolt:9100","connectiontype=gmsec_bolt","loglevel=NONE"]

couchdb:
  restart: always
  image: couchdb:latest
  volumes:
    - ./couchdb:/usr/local/etc/couchdb/init.d
  ports:
    - "5984:5984"

openmct:
  restart: always
  build: ./openmct_server
  links:
    - gm_kerbal_tlm_provider
    - couchdb
  ports:
    - "8080:8080"

# rabbitmq:
#   restart: always
#   build: ./rabbitmq
#   ports:
#     - "80:15672"

# activemq:
#   restart: always
#   image: webcenter/activemq:latest
#   ports:
#     - "8161:8161"
#     - "61616:61616"
#     - "61613:61613"

# gmpub:
#   restart: always
#   build: ./gmsec_pub
#   environment:
#     - LD_LIBRARY_PATH=/GMSEC_API/bin
#   links:
#     - gmbolt
#     - rabbitmq
#   command: ["bash","/code/delay.sh"]
#   #command: ["/GMSEC_API/bin/gmpub","server=gmbolt:5000","iterations=2","connectiontype=gmsec_bolt","interval_ms=500"]
