gmbolt:
  restart: always
  image: chrisreis53/gmsec_node:2-bolt
  command: ["java","-jar","/GMSEC_API/bin/bolt.jar","port=9100"]
  ports:
    - "9100:9100"
  hostname: "gmbolt"
  container_name: "gmbolt"

marklogic:
  restart: always
  build: ./marklogic
  ports:
    - "7997:7997"
    - "7998:7998"
    - "7999:7999"
    - "8000:8000"
    - "8001:8001"
    - "8002:8002"
  hostname: "marklogic"
  container_name: "marklogic"

mysql:
  restart: always
  image: mysql:5.6.26
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=gmsec
  ports:
    - "3306:3306"
  hostname: "mysql"
  container_name: "mysql"

spacecraft_server:
  restart: always
  build: ./example_server
  ports:
    - "8082:8082"
  hostname: "spacecraft_server"
  container_name: "spacecraft_server"

gm_kerbal_adaptor:
  restart: always
  build: ./gmsec_ubuntu
  volumes:
    - ../GMSEC_API-4.2:/GMSEC_API
  environment:
    - LD_LIBRARY_PATH=/GMSEC_API/bin
  links:
    - gmbolt
    - marklogic
  command: ["/GMSEC_API/bin/gm_kerbal_adaptor","server=gmbolt:9100","connectiontype=gmsec_bolt","loglevel=NONE","KERBAL_URL=192.168.0.58"]
  hostname: "gm_kerbal_adaptor"
  container_name: "gm_kerbal_adaptor"

gm_kerbal_tlm_provider:
  restart: always
  build: ./gmsec_ubuntu
  volumes:
    - ../GMSEC_API-4.2:/GMSEC_API
  environment:
    - LD_LIBRARY_PATH=/GMSEC_API/bin
  links:
    - gmbolt
    - marklogic
    - mysql
  ports:
    - "8081:8081"
  command: ["/GMSEC_API/bin/gm_telemetry_server","server=gmbolt:9100","connectiontype=gmsec_bolt","loglevel=NONE"]
  hostname: "gm_kerbal_tlm_provider"
  container_name: "gm_kerbal_tlm_provider"

gmsub:
  restart: always
  build: ./gmsec_sub
  environment:
    - LD_LIBRARY_PATH=/GMSEC_API/bin
  links:
    - gmbolt
  command: ["/GMSEC_API/bin/gmsub","server=gmbolt:9100","connectiontype=gmsec_bolt","loglevel=NONE"]
  hostname: "gmsub"
  container_name: "gmsub"

couchdb:
  restart: always
  image: couchdb:latest
  volumes:
    - ./couchdb:/usr/local/etc/couchdb/init.d
    - ./couchdb/persistant:/usr/local/var/lib/couchdb
  ports:
    - "5984:5984"
  hostname: "couchdb"
  container_name: "couchdb"

openmct:
  restart: always
  build: ./openmct_server
  links:
    - gm_kerbal_tlm_provider
    - couchdb
  volumes:
    - ../openmct:/opt/openmct
  ports:
    - "8080:8080"
  command: ["npm","start"]    
  hostname: "openmct"
  container_name: "openmct"

# rabbitmq:
#   restart: always
#   build: ./rabbitmq
#   ports:
#     - "80:15672"

# activemq:
#   restart: always
#   image: webcenter/activemq:latest
#   ports:
#     - "8161:8161"
#     - "61616:61616"
#     - "61613:61613"

gmpub:
  restart: always
  build: ./gmsec_pub
  environment:
    - LD_LIBRARY_PATH=/GMSEC_API/bin
  links:
    - gmbolt
  #command: ["bash","/code/delay.sh"]
  command: ["/GMSEC_API/bin/gmpub","server=gmbolt:9100","iterations=100","connectiontype=gmsec_bolt","interval_ms=30000","loglevel=NONE"]
  hostname: "gmpub"
  container_name: "gmpub"
