
/*
	gmsec_version.h autogenerated on:
	03/03/2017 09:02:03
*/

#ifndef gmsec_version_h
#define gmsec_version_h

#define GMSEC_VERSION	"GMSEC API v4.2 [03/03/2017]"
#define GMSEC_VERSION_NUMBER "4.2"
#define GMSEC_OS	"Linux 4.4.0-62-generic x86_64"
#define GMSEC_CXX	"gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) "
#define GMSEC_JAVA	"openjdk version 1.8.0_121"
#define GMSEC_PERL	"Perl v5.22.1, gcc, x86_64-linux-gnu-thread-multi"


#ifdef GMSEC_OLD_MACROS

#define OS		"Linux 4.4.0-62-generic x86_64"
#define JAVA_VERSION	"openjdk version 1.8.0_121"
#define C_PLUS_PLUS_VERSION "gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) "

#endif /* GMSEC_OLD_MACROS */

#endif
