# Pull base image.
FROM ubuntu:latest
MAINTAINER Christopher Reis "chrisreis53@gmail.com"

RUN apt update
RUN apt install -y libboost-all-dev libcurl4-openssl-dev

ENV LD_LIBRARY_PATH /GMSEC_API/bin
